### ISSUE TITLE
Implement sync option

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-datastore-fs#1]

**Comment by diasdavid** [comment]
What is the `sync` option?

**Comment by dignifiedquire** [comment]
This refers to the `sync` option available in https://github.com/ipfs/go-ds-flatfs. It means that while writing to disk all files and folders are first synced to disk before continuing write operations. 
This increases reliability in failure cases but slows things down. The current node apis do not expose this in any form (and they are not sync, I checked) so this would need some lowlevel work to allow for this.

**Comment by achingbrain** [comment]
It's been a long time, I guess this wasn't necessary. It can be reopened if it becomes so.
