### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-datastore-fs#6]
Has anyone looked at the dependencies?

Why is `datastore-core`, `level-js`, `leveldown` and `levelup` being referenced? They are not used by the source only by the tests. So at a minimum, they should be moved to devDependencies.  But this also begs the question _"Why are we testing them, if the source code doesn't reference them?_"

Should these tests be moved to `js-ipfs-repo`?

**Comment by diasdavid** [comment]
@dignifiedquire wanna share what were you thinking at the time? Probably leftovers?

**Comment by dignifiedquire** [comment]
You should be able to remove them safely. I probably forgot to clean those out when I split the datastore repos into individual parts.
